### ISSUE TITLE
ERROR: spawnSync java ENOENT when Java not installed

### ISSUE THREAD

**Issue by zommerfelds** [Ribeiro-Tiago/bundletool#17]
Hi, I was running [apkup](https://github.com/eventOneHQ/apkup) and had to debug for a while to find out the issue was in this package and that my Docker image didn't have Java installed.

The error I got is simply `ERROR: spawnSync java ENOENT`.

Might be helpful to check if Java is installed first and print a helpful error message if not?

Let me know if you want a PR for this :)

**Comment by Ribeiro-Tiago** [comment]
Hey, yup I agree. Feel free to set it up, if not I'll work on it when I have the time
