### ISSUE TITLE
Cache binary for future installs

### ISSUE THREAD

**Issue by jpike88** [Ribeiro-Tiago/bundletool#3]
The installer should check ~/.npm folder to see if bundletool binary is already cached instead of downloading each time

**Comment by jpike88** [comment]
relavant reading
https://github.com/sass/node-sass/blob/master/lib/extensions.js
https://github.com/sass/node-sass/pull/1566

**Comment by jpike88** [comment]
Another alternative might be to actually package a copy of the binary in the npm package itself. Yes it increases the payload size, but it means that npm mirror servers will automatically cache it too

**Comment by jpike88** [comment]
@Ribeiro-Tiago any comments on the above?

**Comment by Ribeiro-Tiago** [comment]
@jpike88 No, haven't really had the change to properly look at this yet. But just to confirm, you mean checking the system's npm to see if it's installed globally ?

**Comment by jpike88** [comment]
It wouldn't be a bad idea to check ```.npm``` folder first to see if the binary has already been downloaded in the past, and use that instead of trying to download it again

**Comment by jpike88** [comment]
I see this hasn't been done yet, waiting to bundle tool to install is become a pain. I'm guessing you'll quickly review and handle PRs if they're submitted?

**Comment by jpike88** [comment]
im a dumbass, I made a PR here in the past. I'll do one sometime this week

**Comment by Ribeiro-Tiago** [comment]
yeah I'm sorry I haven't really had the time or the headspace to look into this
