### ISSUE TITLE
EACCES when installing globally

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [Ribeiro-Tiago/bundletool#4]
There's currently an issue with downloading the binary when installing globally:

![image](https://user-images.githubusercontent.com/11082362/92932702-8b95ea00-f445-11ea-8fee-4bfa1915c468.png)

The package gets installed but no binary

**Comment by sarn0ld** [comment]
I get the same error on an alpine/linux-docker-image when installing.
Afterwards  the package can not parse my aab files.

**Comment by sarn0ld** [comment]
A Workaround is to use yarn:

`yarn global add bundletool`

**Comment by Ribeiro-Tiago** [comment]
Closing this issue as I can't really figure out a way to reproduce it (tried mac, different versions of ubuntu and windows), and according to some [research](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) this issue comes from misconfiguration / bad installation of node on linux and the best way to solve is to reinstall node.

Could also validate this as when I reinstalled linux on my work laptop this stopped happening
