### ISSUE TITLE
Error unexpected token when using NCC to build a project

### ISSUE THREAD

**Issue by boswelja** [Ribeiro-Tiago/bundletool#7]
Removing __dirname from below fixes the issue, I'm in the process of testing with my project to find any implications now.
https://github.com/Ribeiro-Tiago/bundletool/blob/4c610bec1c8afa50c51ea1e62c5ff0c0def8051c/constants.js#L5

**Comment by boswelja** [comment]
Small update: The issues seems to be with NCC not being able to handle external deps (like the bundletool jar)

**Comment by Ribeiro-Tiago** [comment]
Good to know, how did you end up solving it (for future reference if someone has the same issue) ?

**Comment by boswelja** [comment]
Honestly I haven't got a solution. I've opened an issue with ncc but in the mean time I've implemented a similar solution in my project directly that downloads bundle tool at run time instead of trying to bundle it on build.
